Repository Codeit-FE3-Part4-team1-Final/Mogazoa, pull requests merged in 2024-04, with the labels that each got.

#11 🌱 : Add File : 전체 이미지 파일 추가
  public/images/add-photo-icon.svg
  public/images/category-icon.svg
  public/images/close-icon.svg
  public/images/dropdown-focus.svg
  public/images/dropdown-nonfocus.svg
  public/images/eyes-close.svg
  public/images/eyes-open.svg
  public/images/google-icon.svg
  public/images/kakao-icon.svg
  public/images/loading-L.svg
  public/images/loading-S.svg
  public/images/logo.svg
  public/images/menu-icon.svg
  public/images/my-profile-icon.svg
  public/images/plus-icon.svg
  public/images/review-icon.svg
  public/images/save-icon.svg
  public/images/search-icon.svg
  public/images/share-icon.svg
  public/images/star-icon.svg
  public/images/thumps-off-icon.svg
  public/images/thumps-on-icon.svg
  public/images/unsave-icon.svg
Labels: 세팅

#20 공통 컴포넌트 - Button 제작
  src/app/profile/[id]/page.tsx
  src/app/profile/me/page.tsx
  src/components/Button/index.module.scss
  src/components/Button/index.tsx
  src/styles/base/_reset.scss
  src/styles/constants/_colors.scss
Labels: 스타일링, 컴포넌트 제작

#22 [비교하기 페이지] Compare Chip 컴포넌트 제작
  package-lock.json
  package.json
  src/app/compare/page.tsx
  src/components/.gitkeep
  src/components/Compare/ObjectChip/ObjectChip.module.scss
  src/components/Compare/ObjectChip/index.tsx
  src/components/Compare/SubjectChip/SubjectChip.module.scss
  src/components/Compare/SubjectChip/index.tsx
Labels: 기능, 컴포넌트 제작

#26 :sparkles: LikeButton 추가
  src/components/LikeButton/cx.ts
  src/components/Thumbs/cx.ts
  src/components/Thumbs/index.module.scss
  src/components/Thumbs/index.tsx
Labels: 컴포넌트 제작

#27 [비교하기 페이지] 테이블 컴포넌트 및 로직 구현
  src/app/compare/page.tsx
  src/components/Compare/Table/Result/Result.module.scss
  src/components/Compare/Table/Result/index.tsx
  src/components/Compare/Table/Table.module.scss
  src/components/Compare/Table/TableCompare/TableCompare.module.scss
  src/components/Compare/Table/TableCompare/index.tsx
  src/components/Compare/Table/index.tsx
Labels: 기능, 스타일링, 컴포넌트 제작

#28 Button 공통 컴포넌트 반응형 스타일, rest props, classNames 적용, CategoryChip 컴포넌트 구현
  src/app/profile/me/page.tsx
  src/components/Button/Button.module.scss
  src/components/Button/index.module.scss
  src/components/Button/index.tsx
  src/components/Chip/CategoryChip/CategoryChip.module.scss
  src/components/Chip/CategoryChip/index.tsx
  src/components/Chip/ObjectChip/ObjectChip.module.scss
  src/components/Chip/ObjectChip/index.tsx
  src/components/Chip/SubjectChip/SubjectChip.module.scss
  src/components/Chip/SubjectChip/index.tsx
  src/types/types.ts
  src/utils/convertCategoryToEnglish.ts
Labels: 스타일링, 리펙토링, 컴포넌트 제작

#30 💄 :feat,style: 사이드바 UI 완료 (반응형O)
  public/images/logo-L.svg
  public/images/logo-S.svg
  public/images/logo.svg
  src/app/test/page.tsx
  src/components/NavigationBar/index.module.scss
  src/components/NavigationBar/index.tsx
  src/styles/mixins/_responsive.scss
Labels: 기능, 스타일링

#29 :sparkles: feat: 텍스트 박스 기능 추가
  public/next.svg
  public/vercel.svg
  src/app/favicon.ico
  src/app/page.tsx
  src/components/Table/Result/Result.module.scss
  src/components/Table/Result/index.tsx
  src/components/Table/Table.module.scss
  src/components/Table/TableCompare/TableCompare.module.scss
  src/components/Table/TableCompare/index.tsx
  src/components/Table/index.tsx
  src/components/TextBox/constants.ts
  src/components/TextBox/cx.ts
  src/components/TextBox/index.module.scss
  src/components/TextBox/index.tsx
Labels: 스타일링, 컴포넌트 제작

#33 API Swagger 문서에 정의된 Type 정의 , Table 컴포넌트 관련 import 경로 수정
  src/components/Table/index.tsx
  src/types/types.ts
Labels: 세팅

#35 ✨ :feat,style : 로그인 페이지 초기 기능 구현 및, UI 완성
  src/app/signin/page.tsx
  src/app/signin/signin.module.scss
  src/app/test/page.tsx
  src/components/Button/index.tsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/NavigationBar/index.tsx
  src/components/SignInput/PasswordInput/PasswordInput.module.scss
  src/components/SignInput/PasswordInput/index.tsx
  src/components/SignInput/UserInfoInput/UserInfoInput.module.scss
  src/components/SignInput/UserInfoInput/index.tsx
  src/styles/mixins/_positions.scss
  src/utils/userValidation.ts
Labels: 기능, 스타일링, 컴포넌트 제작

#39 layout 네비게이션바 적용, ActivityCard 컴포넌트 구현
  src/app/layout.tsx
  src/app/profile/[id]/page.tsx
  src/components/Button/Button.module.scss
  src/components/Card/ActivityCard/ActivityCard.module.scss
  src/components/Card/ActivityCard/index.tsx
  src/components/Chip/CategoryChip/CategoryChip.module.scss
Labels: 스타일링, 리펙토링, 컴포넌트 제작

#41 ProfileCard 컴포넌트 구현, 임시 userDetail 데이터로 테스트, Button 컴포넌트 height 고정
  public/images/profile-image.png
  src/app/profile/[id]/page.tsx
  src/app/profile/me/page.tsx
  src/app/signin/page.tsx
  src/components/Button/Button.module.scss
  src/components/Button/index.tsx
  src/components/Card/ActivityCard/ActivityCard.module.scss
  src/components/Card/ProfileCard/ProfileCard.module.scss
  src/components/Card/ProfileCard/index.tsx
Labels: 스타일링, 컴포넌트 제작

#42 [비교하기 페이지] CompareInput 컴포넌트 구현 및 로직 설정
  package-lock.json
  package.json
  src/apis/getProduct.ts
  src/app/compare/ComparePage.module.scss
  src/app/compare/page.tsx
  src/components/Chip/ObjectChip/ObjectChip.module.scss
  src/components/Chip/SubjectChip/SubjectChip.module.scss
  src/components/Input/CompareInput/CompareInput.module.scss
  src/components/Input/CompareInput/index.tsx
  src/components/Table/Result/Result.module.scss
  src/components/Table/Table.module.scss
  src/components/Table/TableCompare/TableCompare.module.scss
  src/components/Table/TableCompare/index.tsx
  src/components/Table/index.tsx
Labels: 기능

#45 profile page UI, 반응형 디자인 구현
  src/app/compare/page.tsx
  src/app/profile/me/page.module.scss
  src/app/profile/me/page.tsx
  src/components/ActivityDetail/ActivityDetail.module.scss
  src/components/ActivityDetail/index.tsx
  src/components/Card/ActivityCard/ActivityCard.module.scss
  src/components/ProfileProductPanel/ProfileProductPanel.module.scss
  src/components/ProfileProductPanel/index.tsx
  src/types/.gitkeep
  src/utils/.gitkeep
Labels: 스타일링, 리펙토링, 컴포넌트 제작

#48 [프로필 페이지] user id로 userDetail fetch, .env.local 변수 생성
  next.config.mjs
  src/app/mypage/page.tsx
  src/app/profile/[id]/page.tsx
  src/app/user/[id]/error.tsx
  src/app/user/[id]/page.tsx
  src/components/ActivityDetail/index.tsx
  src/components/Card/ActivityCard/index.tsx
  src/components/Card/ProfileCard/index.tsx
  src/components/Chip/CategoryChip/CategoryChip.module.scss
  src/components/ProfileSection/ProfileSection.module.scss
  src/components/ProfileSection/index.tsx
  src/styles/constants/_colors.scss
  src/types/types.ts
  src/utils/convertCategoryToEnglish.ts
  src/utils/getUserDetail.ts
Labels: 기능

#49 ✨ :feat: API 호출 로직 및 로그인 시 로컬스토리지 토큰 저장 기능 구현
  src/apis/postUserInfo.ts
  src/app/home/page.tsx
  src/app/signin/page.tsx
  src/utils/fetchUtils.ts
Labels: 기능

#54 Modal - zustand 전역 상태 관리
  providers/ModalStoreProvider.tsx
  src/app/layout.tsx
  src/components/Card/ProfileCard/ProfileCard.module.scss
  src/components/Card/ProfileCard/index.tsx
  src/components/Modal/ModalWrapper/ModalWrapper.module.scss
  src/components/Modal/ModalWrapper/index.tsx
  src/stores/modalStore.ts
Labels: 기능, 스타일링, 컴포넌트 제작

#56 [비교하기 페이지] api 로직 분리 및 비교하기 페이지 로딩 컴포넌트 구현
  src/apis/.gitkeep
  src/apis/getProduct.ts
  src/apis/getProductDetail.ts
  src/app/compare/ComparePage.module.scss
  src/app/compare/page.tsx
  src/components/Input/CompareInput/ObjectInput/index.tsx
  src/components/Input/CompareInput/SubjectInput/index.tsx
  src/components/Input/CompareInput/index.tsx
  src/components/Loading/CompareLoading/CompareLoading.module.scss
  src/components/Loading/CompareLoading/index.tsx
  src/types/types.ts
  src/utils/fetchUtils.ts
Labels: 기능

#59 [모달] 비교 모달 컴포넌트 구현
  src/app/compare/ComparePage.module.scss
  src/components/Modal/CompareModal/CompareModal.module.scss
  src/components/Modal/CompareModal/index.tsx
Labels: 기능

#66 ✨ :feat:SSR 구현을 위한 엑세스토큰 쿠키관리를 위한 API 로직 수정
  package-lock.json
  package.json
  src/apis/postUserInfo.ts
  src/app/home/page.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/components/NavigationBar/index.tsx
  src/stores/userStore.ts
  src/utils/fetchUtils.ts
  src/utils/userValidation.ts
Labels: 기능, 리펙토링

#64 [상품 상세 페이지] UI 구현
  next.config.mjs
  public/images/star-empty-icon.svg
  src/app/product/[productId]/cx.ts
  src/app/product/[productId]/index.module.scss
  src/app/product/[productId]/page.tsx
  src/components/DropDown/cx.ts
  src/components/DropDown/index.module.scss
  src/components/DropDown/index.tsx
  src/components/Production/cx.ts
  src/components/Production/index.module.scss
  src/components/Production/index.tsx
  src/components/ProductionReview/cx.ts
  src/components/ProductionReview/index.module.scss
  src/components/ProductionReview/index.tsx
  src/components/ProductionStatics/cx.ts
  src/components/ProductionStatics/index.module.scss
  src/components/ProductionStatics/index.tsx
  src/components/Rating/cx.ts
  src/components/Rating/index.module.scss
  src/components/Rating/index.tsx
  src/components/StatisticsCard/constants.ts
  src/components/StatisticsCard/cx.ts
  src/components/StatisticsCard/index.module.scss
  src/components/StatisticsCard/index.tsx
  src/constants/.gitkeep
  src/styles/mixins/_responsive.scss
  src/types/types.ts
Labels: 스타일링, 컴포넌트 제작

#75 💄 :style:홈페이지 ui 구현
  package-lock.json
  package.json
  src/apis/getCategories.ts
  src/app/page.module.scss
  src/app/page.tsx
  src/app/test.ts
  src/components/Card/ProductCard/index.tsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/NavigationBar/index.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/index.tsx
  src/styles/constants/_breakpoints.scss
  src/styles/mixins/_responsive.scss
Labels: 기능, 스타일링

#77 [비교하기 페이지] 버튼 및 테이블 컴포넌트 스타일링 수정
  src/app/compare/ComparePage.module.scss
  src/components/Input/CompareInput/ObjectInput/ObjectInput.module.scss
  src/components/Input/CompareInput/SubjectInput/SubjectInput.module.scss
  src/components/Table/Result/Result.module.scss
  src/components/Table/Table.module.scss
  src/components/Table/TableCompare/index.tsx
  src/components/Table/index.tsx
  src/styles/constants/_colors.scss
Labels: 스타일링

#78 [프로필 페이지] 내 프로필 페이지, 로그아웃, 상품 데이터 불러오기, 유저 페이지로 이동
  next.config.mjs
  src/app/mypage/page.tsx
  src/app/user/[id]/page.tsx
  src/components/Card/ProductCard/index.tsx
  src/components/Card/ProfileCard/ProfileCard.module.scss
  src/components/Card/ProfileCard/index.tsx
  src/components/Input/ImageInput/ImageInput.module.scss
  src/components/Input/ImageInput/index.tsx
  src/components/Input/TextFieldInput/TextFieldInput.module.scss
  src/components/Input/TextFieldInput/index.tsx
  src/components/Modal/EditProfile/EditProfile.module.scss
  src/components/Modal/EditProfile/index.tsx
  src/components/Modal/FollowUserList/index.tsx
  src/components/Profile/ProfileProductCardList/ProfileProductCardList.module.scss
  src/components/Profile/ProfileProductCardList/index.tsx
  src/components/Profile/ProfileProductPanel/ProfileProductPanel.module.scss
  src/components/Profile/ProfileProductPanel/index.tsx
  src/components/Profile/ProfileSection/ProfileSection.module.scss
  src/components/Profile/ProfileSection/index.tsx
  src/hooks/useUserFollowData.ts
  src/hooks/useUserProductData.ts
  src/utils/followUser.ts
  src/utils/getUserDetail.ts
  src/utils/getUserProduct.ts
  src/utils/handleErrorImage.ts
  src/utils/logout.ts
Labels: 기능

#83 [프로필 페이지] 프로필 정보 변경 기능 구현
  package-lock.json
  package.json
  src/components/Card/ProfileCard/ProfileCard.module.scss
  src/components/Card/ProfileCard/index.tsx
  src/components/Input/ImageInput/ImageInput.module.scss
  src/components/Input/ImageInput/index.tsx
  src/components/Input/TextBoxInput/TextBoxInput.module.scss
  src/components/Input/TextBoxInput/index.tsx
  src/components/Input/TextFieldInput/TextFieldInput.module.scss
  src/components/Input/TextFieldInput/index.tsx
  src/components/Modal/EditProfile/EditProfile.module.scss
  src/components/Modal/EditProfile/index.tsx
  src/components/Modal/FollowUserList/FollowUserList.module.scss
  src/components/Modal/FollowUserList/index.tsx
  src/components/NavigationBar/index.tsx
  src/components/TextBox/index.module.scss
  src/hooks/useEditProfile.ts
  src/utils/generateRandomEnglishName.ts
  src/utils/patchProfile.ts
  src/utils/uploadImage.ts
Labels: 기능
