Repository Codeit-FE3-Part4-team1-Final/Mogazoa, pull requests merged in 2024-05, with the labels that each got.

#85 ✨ 프로필 페이지 - 팔로워 목록, 리뷰, 등록한, 좋아요한 상품 목록 무한스크롤 구현, 상품 등록 기능 구현
  package-lock.json
  package.json
  public/images/floating-icon.svg
  src/app/layout.tsx
  src/components/Card/ProfileCard/index.tsx
  src/components/Chip/CategoryChip/index.tsx
  src/components/Floating/Floating.module.scss
  src/components/Floating/index.tsx
  src/components/Input/ImageInput/ImageInput.module.scss
  src/components/Input/ImageInput/index.tsx
  src/components/Input/Select/Select.module.scss
  src/components/Input/Select/index.tsx
  src/components/Input/SelectOptions/SelectOptions.module.scss
  src/components/Input/SelectOptions/index.tsx
  src/components/Input/TextBoxInput/TextBoxInput.module.scss
  src/components/Input/TextBoxInput/index.tsx
  src/components/Input/TextFieldInput/index.tsx
  src/components/Modal/CreateProduct/CreateProduct.module.scss
  src/components/Modal/CreateProduct/index.tsx
  src/components/Modal/EditProfile/EditProfile.module.scss
  src/components/Modal/EditProfile/index.tsx
  src/components/Modal/FollowUserList/index.tsx
  src/components/Modal/ProfileFollowModal/index.tsx
  src/components/Production/index.tsx
  src/components/Profile/ProfileProductCardList/index.tsx
  src/components/Profile/ProfileProductPanel/index.tsx
  src/hooks/useCreateProduct.ts
  src/hooks/useEditProfile.ts
  src/hooks/useInfiniteFollow.ts
  src/hooks/useInfiniteUserProduct.ts
  src/hooks/useUserFollowData.ts
  src/hooks/useUserProductData.ts
  src/stores/modalStore.ts
  src/stores/sidebarStore.ts
  src/types/types.ts
  src/utils/convertCategoryToEnglish.ts
  src/utils/createProduct.ts
  src/utils/getUserDetail.ts
  src/utils/getUserFollowList.ts
  src/utils/getUserProduct.ts
  src/utils/patchProfile.ts
  src/utils/validateProductName.ts
Labels: 기능, 스타일링, 리펙토링, 컴포넌트 제작

#88 [홈페이지]-네비게이션바 완료, 사이드바 완료, 카테고리별 홈페이지 완료
  src/app/page.module.scss
  src/app/page.tsx
  src/components/Card/HomeProductCard/HomeProductCard.module.scss
  src/components/Card/HomeProductCard/index.tsx
  src/components/Card/RankingCard/RankingCard.module.scss
  src/components/Card/RankingCard/index.tsx
  src/components/Chip/RankingChip/RankingChip.module.scss
  src/components/Chip/RankingChip/index.tsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/NavigationBar/index.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/index.tsx
  src/stores/searchStore.ts
  src/stores/searchValueStore.ts
  src/stores/sidebarStore.ts
  src/styles/constants/_breakpoints.scss
  src/styles/constants/_colors.scss
Labels: 기능, 스타일링, 리펙토링, 버그수정

#93 [상품 상세 페이지] 리뷰 기능 추가
  src/app/product/[productId]/actions.ts
  src/app/product/[productId]/page.tsx
  src/components/Production/index.module.scss
  src/components/Production/index.tsx
  src/components/ProductionReview/actions.ts
  src/components/ProductionReview/index.module.scss
  src/components/ProductionReview/index.tsx
  src/components/ReviewItem/cx.ts
  src/components/ReviewItem/index.module.scss
  src/components/ReviewItem/index.tsx
  src/components/Thumbs/action.ts
  src/components/Thumbs/index.tsx
Labels: 기능

#95 [세팅] 색깔 변수 추가
  src/styles/constants/_colors.scss
Labels: 세팅

#99 [비교 모달] 상품 id 연동 및 스타일 추가
  src/components/Modal/CompareModal/CompareModal.module.scss
  src/components/Modal/CompareModal/index.tsx
  src/components/Production/index.tsx
Labels: 스타일링, 버그수정

#98 [사이드바,네비게이션바]-검색창 토글 기능, ui 리팩토링, 사이드바 유저기능 버튼 추가
  public/images/logo-image.svg
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/components/Home/CategoryMain/CategoryMain.module.scss
  src/components/Home/CategoryMain/CategoryMain.tsx
  src/components/Home/CommonMain/CommonMain.module.scss
  src/components/Home/CommonMain/CommonMain.tsx
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/NavigationBar/index.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/index.tsx
  src/stores/searchStore.ts
  src/styles/constants/_colors.scss
Labels: 기능, 리펙토링

#100 [홈페이지] - 홈페이지 매인 화면 구성
  public/images/logo-image.svg
  src/app/page.module.scss
  src/app/page.tsx
  src/components/Home/CategoryMain/CategoryMain.module.scss
  src/components/Home/CategoryMain/CategoryMain.tsx
  src/components/Home/CommonMain/CommonMain.module.scss
  src/components/Home/CommonMain/CommonMain.tsx
  src/components/NavigationBar/index.tsx
  src/components/SideBar/SideBar.module.scss
  src/components/SideBar/index.tsx
  src/components/YouTubeEmbeb/YouTubeEmbed.tsx
Labels: 기능, 스타일링, 리펙토링

#101 ✨ 리뷰, 등록, 찜한 상품, 팔로워 목록 없을 때 UI 제작, 유저 기본 이미지 변경, 프로필 이미지 최초변경 시 버그 수정
  src/components/Card/ProductCard/index.tsx
  src/components/Card/ProfileCard/index.tsx
  src/components/Modal/FollowUserList/index.tsx
  src/components/Modal/ProfileFollowModal/index.tsx
  src/components/Profile/ProfileProductCardList/index.tsx
  src/components/Profile/ProfileProductPanel/index.tsx
  src/components/Skeleton/NoFollow/NoFollow.module.scss
  src/components/Skeleton/NoFollow/index.tsx
  src/components/Skeleton/NoProduct/NoProduct.module.scss
  src/components/Skeleton/NoProduct/index.tsx
  src/hooks/useEditProfile.ts
  src/utils/handleErrorImage.ts
Labels: 기능, 리펙토링, 버그수정

#105 [홈페이지]-기본 메인 페이지 반응형 완료
  src/app/page.tsx
  src/components/Home/CategoryMain/CategoryMain.module.scss
  src/components/Home/CategoryMain/CategoryMain.tsx
  src/components/Home/CommonMain/CommonMain.module.scss
  src/components/Home/CommonMain/CommonMain.tsx
  src/components/NavigationBar/index.tsx
  src/components/YouTubeEmbeb/YouTubeEmbed.tsx
Labels: 기능, 스타일링

#106 [세팅] 탑 스크롤 버튼 컴포넌트 및 푸터 컴포넌트 구현
  public/images/arrow-top.svg
  src/components/Button/TopScroll/TopScroll.module.scss
  src/components/Button/TopScroll/index.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/index.tsx
  src/components/Input/CompareInput/CompareInput.module.scss
  src/components/Input/CompareInput/index.tsx
Labels: 기능, 스타일링, 세팅

#104 [상세페이지] 리뷰 등록 및 수정 기능 추가
  package-lock.json
  package.json
  src/app/product/[productId]/page.tsx
  src/components/Modal/CreateReview/cx.ts
  src/components/Modal/CreateReview/index.module.scss
  src/components/Modal/CreateReview/index.tsx
  src/components/Modal/EditReview/cx.ts
  src/components/Modal/EditReview/index.module.scss
  src/components/Modal/EditReview/index.tsx
  src/components/Production/index.module.scss
  src/components/Production/index.tsx
  src/components/ProductionReview/actions.ts
  src/components/ProductionReview/index.module.scss
  src/components/ProductionReview/index.tsx
  src/components/ReviewItem/index.module.scss
  src/components/ReviewItem/index.tsx
  src/components/ReviewRating/cx.ts
  src/components/ReviewRating/index.module.scss
  src/components/ReviewRating/index.tsx
  src/components/Skeleton/NoFollow/NoFollow.module.scss
  src/components/Skeleton/NoFollow/index.tsx
  src/components/Skeleton/NoProduct/NoProduct.module.scss
  src/components/Skeleton/NoProduct/index.tsx
  src/hooks/useCreateReview.ts
  src/hooks/useEditReview.ts
  src/types/types.ts
  src/utils/createReview.ts
  src/utils/deleteReview.ts
  src/utils/updateReview.ts
Labels: 기능

#109 ✨ Product 편집 기능 구현
  src/components/Input/ImageInput/index.tsx
  src/components/Input/Select/index.tsx
  src/components/Modal/CreateProduct/index.tsx
  src/components/Modal/ModalWrapper/index.tsx
  src/components/Modal/ProfileFollowModal/ProfileFollowModal.module.scss
  src/components/Modal/ProfileFollowModal/index.tsx
  src/components/Production/index.tsx
  src/components/Profile/ProfileProductPanel/index.tsx
  src/hooks/useCreateProduct.ts
  src/utils/createProduct.ts
  src/utils/getUserToken.ts
  src/utils/validateProductName.ts
Labels: 기능, 리펙토링

#111 ✨ 카카오톡 공유하기/간편로그인/회원가입 기능 구현, 간편로그인(카카오톡) 회원가입을 위한 페이지 제작
  providers/KakaoScript.tsx
  src/app/layout.tsx
  src/app/oauth/signup/[provider]/OAuthSignup.module.scss
  src/app/oauth/signup/[provider]/page.tsx
  src/app/signin/page.tsx
  src/app/signin/signin.module.scss
  src/components/Input/UserInfoInput/UserInfoInput.module.scss
  src/components/OAuth/SignupToKakao/SignupToKakao.module.scss
  src/components/OAuth/SignupToKakao/index.tsx
  src/components/Production/index.tsx
  src/pages/.gitkeep
  src/pages/api/auth/kakao-signin.ts
  src/pages/api/auth/kakao-signup.ts
  src/types/types.ts
  src/utils/SigninKakao.ts
  src/utils/setCookieOAuth.ts
  src/utils/shareKakao.ts
  src/utils/signupToKakao.ts
Labels: 기능

#115 🐛 카카오 로그인 URI 수정
  src/app/signin/page.tsx
  src/pages/api/auth/kakao-signin.ts
  src/pages/api/auth/kakao-signup.ts
  src/utils/signinToKakao.ts
Labels: 버그수정
